### ISSUE TITLE
SwiftKey support

### ISSUE THREAD

**Issue by Landxhent** [Traurige/Kayoko#1]
**Describe the requested feature:**
Swiftkey app (3rd party keyboard) support, if possible, as well as visual customization, like the way Copypasta possible: to remove bar/chevron, change background colour/transparency
**System information:**
- iOS version:14.1
- Jailbreak:Taurine 1.1.6

**Comment by Traurige** [comment]
Sorry buddy, but I already made my mind up about third party keyboards not getting support. I also won't add random customization to everything like I used to.
