### ISSUE TITLE
Kayoko sends me straight to safe mode

### ISSUE THREAD

**Issue by Oliverkiller** [Traurige/Kayoko#10]
Kayoko sends me to safe mode if I am not using libhooker-shim from Havoc Repo 

Device: iPhone 6s
iOS version: 15.1
Jailbreak: Palera1n 
[Crashlog](https://github.com/Traurige/Kayoko/files/10312250/Note.2022-12-28.07-11-30.txt)

**Comment by Oliverkiller** [comment]
Note: The log itself doesn’t identify that it’s Kayoko but after enabling and disabling tweaks one by one using choicy I reached this conclusion

**Comment by Traurige** [comment]
Are you using the no-daemon version?

**Comment by Traurige** [comment]
I can't get palera1n to work on any of my devices. I decided to kill palera1n support. I had gotten it to work once, but due to banking security I had to unjailbreak one of my devices and now it doesn't work anymore. While the palera1n doesn't support daemons it will presumably not work.

**Comment by Oliverkiller** [comment]
Yes I was using the no-daemon version
