### ISSUE TITLE
Doesn’t seem to function with predictive text, and doesn’t show in all apps with dictation. 

### ISSUE THREAD

**Issue by Anthokneee** [Traurige/Kayoko#12]
**Describe the bug:**
When predictive text is selected I can’t access the history or invoke the tweak at all. When dictation is selected it works in spotlight and certain apps but doesn’t in most third party apps and settings. 

**Steps to reproduce the behavior:**

**Crash log:**
Upload your log file to pastebin and paste the link here.

**System information:**
- iOS version:15.1.1
- Device:iPhone 13 Pro Max
- Jailbreak:Xina 1.1.6.2

**Comment by Traurige** [comment]
#7 and #9
