### ISSUE TITLE
“Service is disabled”

### ISSUE THREAD

**Issue by monobo1989** [Traurige/Kayoko#14]
**Describe the bug:**
History is empty.
Possible cause: Daemon not loaded: https://s1.ax1x.com/2023/02/11/pS45DmR.jpg

**Steps to reproduce the behavior:**

**Crash log:**

**System information:**
- iOS version: 13.7
- Device: iPhone XS
- Jailbreak: unc0ver

**Comment by Traurige** [comment]
Try loading the damon yourself via terminal: `launchctl load /Library/LaunchDaemons/dev.traurige.kayokod.plist`

**Comment by monobo1989** [comment]
> Try loading the daemon yourself via terminal: `launchctl load /Library/LaunchDaemons/dev.traurige.kayokod.plist`

Thanks , But the error message appears again: https://s1.ax1x.com/2023/02/12/pS5CV76.jpg
What should I do

**Comment by Traurige** [comment]
You may need to add the `-w` option then.

**Comment by monobo1989** [comment]
> You may need to add the `-w` option then.
I don't know what to do : https://pic.lovlss.top/i/2023/02/12/f1dn11.webp
I feel like I'm giving up

**Comment by monobo1989** [comment]
> You may need to add the `-w` option then.

Thanks, I have solved it.
launchctl load -w /Library/LaunchDaemons/dev.traurige.kayokod.plist
