### ISSUE TITLE
Can u add this new options ?

### ISSUE THREAD

**Issue by MiladShojaei** [Traurige/Kayoko#15]
**Describe the requested feature:**

**System information:**
- iOS version:14.3
- Device: iphone 12 pro
- Jailbreak: Unc0ver

1 : add a new option to touch outside of history to de active history
2 : add a new toggle for SwipeExtenderx to active or for activator 
3 : a feature to reorganize favorites “ reorder them”

thanks

**Comment by Traurige** [comment]
None of these will be added.
