### ISSUE TITLE
Kayoko on IPad’s landscape mode

### ISSUE THREAD

**Issue by OmegaTwo** [Traurige/Kayoko#17]
**Describe the bug:** Kayoko interface is stuck in the bottom left corner with only ~25% of the interface showing, making it very difficult to scroll through or dismiss.

**Steps to reproduce the behavior:** Invoke Kayoko on iPad Pro 2020 while in landscape mode.

![53AAA2E4-44B8-47AE-BEAB-9F551ADC57EC](https://user-images.githubusercontent.com/127713511/224609541-8582070c-9075-4188-9128-4b11c5c98497.jpeg)

**System information:**
- iOS version: 15.1
- Device: iPad Pro 2020 (Wi-Fi model)
- Jailbreak: XinaA15

**Comment by Traurige** [comment]
#6
