### ISSUE TITLE
 iPad landscape mode support?

### ISSUE THREAD

**Issue by koyomi0912** [Traurige/Kayoko#22]
**System information:**
- iOS version: 15.4.1
- Device: iPad Pro (11-inch, 3rd generation)
- Jailbreak: Dopamine

**Describe the requested feature:**

can you add support for iPad on landscape mode?
If not, I will understand. If you can, I'll wait patiently, there's no rush.

Please also note that there is a screen orientation issue.
![IMG_3884](https://github.com/Traurige/Kayoko/assets/46727658/8711b648-1906-47b9-ac53-d3ae661e6a34)
![IMG_3883](https://github.com/Traurige/Kayoko/assets/46727658/cf12d30b-ad23-4c98-80eb-889b43b1d4fc)
![IMG_3880](https://github.com/Traurige/Kayoko/assets/46727658/6f48c9b2-a01f-46a6-9168-707ab3fa4f81)

have a nice day traurige/litten, i missed your amazing tweaks :D

edit: ok i just realized that having copypasta installed on my iphone had same problem of landscape mode. I guess it's a problem that can't be fixed? :c

**Comment by Traurige** [comment]
#6
