### ISSUE TITLE
Copied items don’t show in the history

### ISSUE THREAD

**Issue by jsc371058962** [Traurige/Kayoko#24]
**Describe the bug:**
Copied items don’t show in the history.

![18931D6E-ED57-4FC8-8C13-C9F1875E6862](https://github.com/Traurige/Kayoko/assets/33423057/137db10f-2fbf-4167-86c0-a463a0673df5)

**Steps to reproduce the behavior:**
Copy/Cut anything.

**System information:**
- iOS version: 15.0
- Device: 12 Pro
- Jailbreak: Dopamine

**Comment by Traurige** [comment]
Try running this in terminal:
`launchctl load -w /var/jb/Library/LaunchDaemons/dev.traurige.kayokod.plist`

**Comment by Traurige** [comment]
I will close this issue in five days if no answer is provided. @jsc371058962
