### ISSUE TITLE
Apps crashing when launching

### ISSUE THREAD

**Issue by RatedR9** [Traurige/Kayoko#26]
**Describe the bug:**
Apps crashing when launching

**Steps to reproduce the behavior:**

**Crash log:**
Upload your log file to pastebin and paste the link here.
One of crashed app log file
https://pastebin.com/raw/UnnBTP7A

**System information:**
- iOS version: 15.4.1 
- Device: 12 Pro
- Jailbreak: Dopamine

**Comment by RatedR9** [comment]
yes ,latest version ,but sometimes happen ,can I use other app to chat with you?

**Comment by Traurige** [comment]
All my contact information is linked to my profile.

**Comment by RatedR9** [comment]
ok, I have sent discord friend request please check it

**Comment by Traurige** [comment]
I can see this myself now. I've actually been experiencing this too without noticing. I thought the apps were getting killed to free memory, but it turns out the helper does crash processes.

**Comment by Traurige** [comment]
May be related to #28

**Comment by Traurige** [comment]
This has not been fixed yet, and thus shall not be closed.

**Comment by Traurige** [comment]
@RatedR9 does this fix the crashes?

https://traurige.dev/dev.traurige.kayoko_1.4.2-14+debug_iphoneos-arm64.deb

**Comment by RatedR9** [comment]
I don't understand why you deleted me on discord. To be honest, I'm not really interested in any of this right now .because I have a lot of tweaks installed and installing kayoko makes the phone fragile and because I already have copylog installed so there's no point in installing another of the same tweak.although copylog has some shortcomings but it feels fine once I get used to it. Thanks for all your hard work.

**Comment by Traurige** [comment]
I delete 98% of people again. I also nuke my messages. It’s nothing personal. But alright, if that’s how this is gonna be, then be it.

**Comment by RatedR9** [comment]
Can you recommend me some anime that you think look good? I think you have good taste. Thank you.

**Comment by Traurige** [comment]
You can ask me that anywhere else, but not GitHub issues haha.

**Comment by RatedR9** [comment]
I can’t get touch with u from anywhere else, but why not here? It's so
rigid. People are alive. Isn't it good to be free and talk anywhere else?

Alexandra ***@***.***>于2023年11月13日 周一05:23写道：

**Comment by Traurige** [comment]
Why? Because GitHub Issues is not a chatting platform. Here’s all ways of talking to me: https://linktr.ee/vyolit

**Comment by RatedR9** [comment]
I know,but the issue was closed,so don’t care

Alexandra ***@***.***>于2023年11月13日 周一22:07写道：
