### ISSUE TITLE
复制过程中会安全模式

### ISSUE THREAD

**Issue by liyu-sir** [Traurige/Kayoko#27]
复制过程中会安全模式

**System information:**
- iOS version: ios15.2
- Device: iphone11promax
-Jailbreak: Dopamine

**Comment by Traurige** [comment]
I don’t speak chinese.

**Comment by liyu-sir** [comment]
1. It will be safe mode during the copy and paste process.
2. Copy function has no effect.
3. Use the paste function before copying the content, it will flash back.
4. During use, it occasionally causes the system to reboot, after uninstallation, no such situation is triggered, just guessing.
