### ISSUE TITLE
Program crashes, device restarts, etc

### ISSUE THREAD

**Issue by liyu-sir** [Traurige/Kayoko#28]
**Describe the bug:**
1. Safe mode when copying and pasting
2. The copy suggestion doesn't work
3. Use the paste function before copying the content, it will flash back. ????
4. Random reboots

**Crash log:**

**System information:**
iOS version: iOS 15.2
Device: iPhone 11 Pro Max
Jailbreak: Dopamine

**Comment by Traurige** [comment]
You experience crashes. I expect a crash log like the template says.
