### ISSUE TITLE
Nothing i copy gets added to history

### ISSUE THREAD

**Issue by Hamzabdx** [Traurige/Kayoko#31]
**Describe the bug:** after updating to version 1.4 whatever i copy doesnt show in history and cant fix this by downgrading either

**Steps to reproduce the behavior:**

**Crash log:**
Upload your log file to pastebin and paste the link here.
This maybe : https://pastebin.com/jsKshGQT
**System information:**
- iOS version:15.0
- Device:iphone 13 pro max
- Jailbreak:xinaa12

**Comment by Traurige** [comment]
Run `launchctl load -w /var/jb/Library/LaunchDaemons/dev.traurige.kayokod.plist `

**Comment by Hamzabdx** [comment]
It says : " operation not permitted "

**Comment by Traurige** [comment]
Run it as super user.

**Comment by Hamzabdx** [comment]
Ok i added sudo and it worked thanks
