### ISSUE TITLE
Kayoko activating when I don't need it to

### ISSUE THREAD

**Issue by nn9dev** [Traurige/Kayoko#35]
**Describe the bug:** 
This bug has been around for a while, but for some reason when I tap on a specific area of the screen, Kayoko activates. It doesn't happen in ALL apps, but it does in Safari, which makes it particularly annoying to browse the web.

**Steps to reproduce the behavior:**
Open Safari, activate the keyboard in some form or fashion and then un-activate it (seems to activate the bug if I tap the URL bar and then hit cancel), then tap around this area, maybe a little higher
![image](https://github.com/Traurige/Kayoko/assets/39563889/6d584502-1412-4930-8a9b-8d49aa87fba0)

**Crash log:**
N/A

**System information:**
- iOS version: 14.5.1
- Device: iPhone SE 2020
- Jailbreak: unc0ver with Fugu14 untether

**Comment by nn9dev** [comment]
(I have no idea if this is related to #11 since the video they posted seems to be gone now)

**Comment by Traurige** [comment]
I’m not able to reproduce it with your provided information. And yes, it’s the same issue as in #11, and thus will be closed.

**Comment by minhnh10x** [comment]
I've encountered a similar bug, but only when using the Dictation Key activation method
