### ISSUE TITLE
apps crashing after installing the tweak

### ISSUE THREAD

**Issue by abdothiss** [Traurige/Kayoko#5]
**Describe the bug:**
every app crashes after installing the tweak except for apps like selio trollstore etc
**Steps to reproduce the behavior:**

**System information:**
- iOS version: ios15.4
- Device: A10
- Jailbreak: palera1n

**Comment by Traurige** [comment]
Which version of Kayoko did you install? The daemon or the no-daemon version?

**Comment by abdothiss** [comment]
> Which version of Kayoko did you install? The daemon or the no-daemon version?

the no daemon vers, i haven't tried the daemon one

**Comment by Traurige** [comment]
Yeah. Please try if that one still crashes your apps (it will not function though).

**Comment by abdothiss** [comment]
> Yeah. Please try if that one still crashes your apps (it will not function though).

i did but but once i clicked restart springboard it stuck there, i had to rejailbreak . seems like there is no way to get it to work .

**Comment by Traurige** [comment]
I’ll need a crash report to have a chance of helping you. This hasn’t happened to anyone else.

**Comment by Traurige** [comment]
I will close this if no crash report is provided by Friday.
