### ISSUE TITLE
Add rotation support

### ISSUE THREAD

**Issue by Andy312432** [Traurige/Kayoko#6]
Like to title, screenshot :

![F55478B5-A79A-40E5-9AED-C8B831D9706D](https://user-images.githubusercontent.com/31586206/206713089-1378bd9d-0dc8-41cb-bc02-04a1a346b822.png)

System information:
- iOS version:15.1
- Device:iPad pro m1
- Jailbreak:xina

Again, thanks for the great tweak!!

**Comment by Traurige** [comment]
Does it align correctly when you put it into portrait mode?

**Comment by Andy312432** [comment]
Yes it does!! Almost forgot portrait mode since I can’t rotate the screen easily after jailbreak lmao

**Comment by Traurige** [comment]
That’s good, it only needs rotation support added then. Would you mind adding me on discord so we can get it working together (you can find my tag on my profile readme)?

**Comment by Andy312432** [comment]
Sure! I’m 312321321321432#5761, sent the friend request.

**Comment by OmegaTwo** [comment]
Hi! I came over from my other post. Apologies, I didn’t know the query was opened before. If you need any help troubleshooting then please let me know. Would love to help, and thank you very much for the amazing tweak you built!

**Comment by F-Unction** [comment]
![DE318996-4D8B-4791-BF86-8DA8BB162D3A](https://user-images.githubusercontent.com/51352133/236633059-d77b3363-eb5a-4dbf-bfb6-70bcd8bbca68.png)
This also needs a fix.

**Comment by Traurige** [comment]
#30
