### ISSUE TITLE
Kayoko has an invalidation problem

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [Traurige/Kayoko#8]
Kayoko is using XinaA15 v1.1.4 jailbreak, it is invalid in the third-party app, but it is valid in the system app.

- iOS version:15.1
- Jailbreak:XinaA15 v1.1.4

**Comment by Traurige** [comment]
I have no idea what you're trying to say.

**Comment by xiangfeidexiaohuo** [comment]
> I have no idea what you're trying to say.

I use ios15 device, xina jailbreak tool v1.1.4.

Kayoko Enable Dictation Key，In third-party applications, such as wechat, Kayoko cannot be woken up using the dictation key.

**Comment by Traurige** [comment]
Does it work with the previous version of Xina?

**Comment by xiangfeidexiaohuo** [comment]
> 

xina v1.1.36 is ok！
But it may also fail suddenly,It is ok after the device respringa.

**Comment by Traurige** [comment]
Doesn’t sound like an issue from Kayoko itself then.

**Comment by Traurige** [comment]
I tried it myself and it works fine on previous version, but not in user apps on the latest. I have also seen other tweaks not working on the latest version. I will close this as it seems to be a Xina problem.
