### ISSUE TITLE
The dictation key method doesn’t work in all apps

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [Traurige/Kayoko#9]
**System information:**
- iOS version: iOS14.1  and 15.1
- Jailbreak: unc0ver and XinaA15 v1.1.5

Install Kayoko v1.1 in safe mode.
Both devices are the same.

xina use no-daemon v1.1，no safe mode，but use the dictation key, still cannot use the clipboard in third-party apps.

**Comment by Traurige** [comment]
I need a crash log.

**Comment by xiangfeidexiaohuo** [comment]
> I need a crash log.

[15.1.log](https://github.com/Traurige/Kayoko/files/10297922/15.1.log)

**Comment by mansonstein1** [comment]
> **System information:**
> 
> * iOS version: iOS14.1  and 15.1
> * Jailbreak: unc0ver and XinaA15 v1.1.5
> 
> Install Kayoko v1.1 in safe mode. Both devices are the same.
> 
> xina use no-daemon v1.1，no safe mode，but use the dictation key, still cannot use the clipboard in third-party apps.

Exactly the same

**Comment by Traurige** [comment]
I uploaded 1.1 again. Can you try if that works now?

Note: palera1n is not supported anymore.

**Comment by xiangfeidexiaohuo** [comment]
> I uploaded 1.1 again. Can you try if that works now?
> 
> Note: palera1n is not supported anymore.

The new v1.1 has been tested and will not be in safe mode.

But on xina jailbreak, the dictation key still cannot call out the clipboard in the third-party app.

**Comment by xiangfeidexiaohuo** [comment]
Today, xina updated rocketbootstrap_ 1.0.10~beta2，Kayoko is fully working.

**Comment by Traurige** [comment]
Good to know it's not an issue of Kayoko itself. Thanks for letting us know. I will close this issue now.
